# Generated by Django 6.0.5 on 2026-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
