# Generated by Django 6.0.5 on 2026-05-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
