# Generated by Django 6.0.5 on 2026-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0003_delete_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3)),
                ('author', models.CharField(max_length=2)),
                ('description', models.TextField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
