# Generated by Django 6.0.5 on 2026-05-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
